#!/bin/bash
# Copyright (c) 2017 Square Panda Inc.
# All Rights Reserved.
# Dissemination, use, or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from Square Panda Inc.
# @Last modified by:   Singh Saurabh
#
# Setup for stream-processing-service

# Ensures a python pip package is installed.  The function first checks to see if
# the package is already installed.  If not, the package is installed.  Requires
# that pip3 is installed.  May exit if errors are encountered.
# Globals:
#   None
# Arguments:
#   $1: Name of package to check.  Must match exactly what is used to install the
#       package with pip3.
# Returns:
#   None
function check_pip_package {
  local package_name=$1
  pip_package_check=$(pip3 list | grep ${package_name})
  if [[ ! -z "${pip_package_check}" ]]; then
    echo "Required pip lib is installed: ${pip_package_check}"
    return
  fi

  echo "Installing ${package_name}"
  pip3 install ${package_name}
  result="$?"
  if [[ "${result}" != "0" ]]; then
    echo "ERROR: failed to install ${package_name}"
    exit ${result}
  fi
}

echo "Starting initialization"

# Python 3.5 is required
python_check=$(command -v python3)
if [[ ! -z "${python_check}" ]]; then
  echo "Python is available: ${python_check}"
else
  echo "Installing python3"
  sudo apt-get update
  yes | sudo apt-get install python3.5
  result="$?"
  if [[ "${result}" != "0" ]]; then
    echo "ERROR: failed to install python3"
    exit ${result}
  fi
fi

# Python pip required
pip_check=$(command -v pip3)
if [[ ! -z "${pip_check}" ]]; then
  echo "Python pip is available: ${pip_check}"
else
  echo "Installing python pip3"
  sudo apt-get update
  yes | sudo apt-get install python3-pip
  result="$?"
  if [[ "${result}" != "0" ]]; then
    echo "ERROR: failed to install pip3"
    exit ${result}
  fi
fi

check_pip_package "sqlalchemy"
check_pip_package "linecache"
check_pip_package "pandas"
check_pip_package "psycopg2"
check_pip_package "s3fs"

mkdir -p /home/ubuntu/logs/
mkdir -p /home/ubuntu/ipproject

echo "Completed initialzation"
