#!/bin/bash
# Copyright (c) 2017 Square Panda Inc.
# All Rights Reserved.
# Dissemination, use, or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from Square Panda Inc.
# @Last modified by:   Singh Saurabh

pgrep -f resolve_ip.py
if [[ "$?" == "1" ]]; then
  echo "No processing running"
  exit
fi

echo "Stopping running service"
pkill -f resolve_ip.py
exit $?
